### ISSUE TITLE
Task and TODO for SWE22_23

### ISSUE THREAD

**Issue by akodakkal** [mpentek/SWELecture#2]
### Organizational tasks
- [x] Registration - Answer emails etc . - **AK** 
- [x] make MP and GML as cohosts
- [x] Send email with the procedure to add to moodle, requesting personal presence etc - **AK**
- [x] Adding students to moodle - **GML**
- [x] Attendance register preparation and maintenance - **AK** 
- [ ] Organization issues – exam registration, organizing exams
- [x] Organization of groups – How to choose the project groups
- [x] Project topics – which buildings
- [ ] Organization of feedback
- [ ] Gid licenses for students
- [ ] Organize excursion
- [ ] Organize invited lecture
### Moodle and sync and share tasks 
- [x] Moodle updating and migrating contents - **GML** 
- [x] Moodle calendar updating to match deadlines 
- [x] Sync and share updating - **AK** 
- [x] Updating organizational documents, dates etc. **GML** **AK**
- [x] Updating the title slides, footnotes etc. **AK** 
### Teaching and tutorial related tasks 
- [x] Talking to Enis - End of sept
- [ ] Verifying Enis tasks with CAARC and CFD tutorial **AK&GML** 
- [x] Updating the worksheets and video disclaimers – **AK***
- [ ] Updating GID16 installation guides and check all the codes work CFD, FSI, custom FSI - **Enis** + **AK/GML**
- [ ] Cluster wiki and providing tutorial **GML**
- [ ] Updating tutorial regarding project work post processing – **Enis**
- [ ] Paraview post processing guide **Enis**
- [ ]  Combining all the installation guides with project specific guidelines etc to have a complete project handbook  - Enis (the hitchhikers guide to SWE with Kratos ) - open document - TODO
- [ ] updating animation in Paroptbeam – **AK**
- [ ] Cluster related task – **GML**
- [ ] MCQ, CYK, OEQ – **Enis**

**Comment by akodakkal** [comment]
@mpentek @mtnzguillermo  please add to the list.
